/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#006880",
        "primary-fixed": "#72d9fd",
        "primary-fixed-dim": "#63cbee",
        "primary-container": "#72d9fd",
        "on-primary": "#f1faff",
        "on-primary-container": "#004a5d",
        secondary: "#506076",
        "secondary-container": "#d3e4fe",
        "on-secondary": "#f7f9ff",
        "on-secondary-container": "#435368",
        tertiary: "#006b60",
        "tertiary-container": "#65fde6",
        "on-tertiary": "#e2fff8",
        "on-tertiary-container": "#005e54",
        surface: "#f7fafc",
        "surface-dim": "#d2dbe0",
        "surface-bright": "#f7fafc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4f7",
        "surface-container": "#e8eff3",
        "surface-container-high": "#e2e9ed",
        "surface-container-highest": "#dbe4e9",
        "surface-variant": "#dbe4e9",
        "on-surface": "#2b3438",
        "on-surface-variant": "#576065",
        outline: "#737c80",
        "outline-variant": "#aab3b8",
        error: "#a83836",
        "error-container": "#fa746f",
        "on-error": "#fff7f6",
        "on-error-container": "#6e0a12",
        background: "#f7fafc",
        "on-background": "#2b3438",
        "inverse-surface": "#0b0f11",
        "inverse-on-surface": "#9a9da0",
        "inverse-primary": "#72d9fd",
      },
    },
  },
  plugins: [],
};
